### ISSUE TITLE
Rename .cp -> .fold

### ISSUE THREAD

**Issue by edemaine** [edemaine/cp-editor#9]
FOLD 1.2 now supports `"C"` edges so we can use that as our primary format.
It's still helpful to have a "Save as exploded FOLD" or similar wording to switch from `"C"` to `"B"`.

**Comment by LYXSUPER** [comment]
Now I can not use it,It is terrible.

**Comment by edemaine** [comment]
Could you clarify what you mean? This is just a renaming of file extensions. What is the workflow that you're trying to get working?

**Comment by LYXSUPER** [comment]
> 你能澄清一下你的意思吗？这只是文件扩展名的重命名。您尝试开始工作的工作流程是什么？

Before, I couldn’t edit creases online through the URL, but today I can, but there are still problems that cannot be simulated by the origami simulator，Through the simulation button of the crease editor, he jumps to the simulator without responding

**Comment by LYXSUPER** [comment]
> Through the simulation button of the crease editor, he jumps to the simulator without responding

**Comment by edemaine** [comment]
Oh, I think I see what the problem was. It should be fixed now.
